HTML-CSS-JS/js-form/config/routes.rb
Rails.application.routes.draw do
  resources :users
  match "/signup", :to => "users#signup", :via => :get
  get "/signin" => 'users#signin'
  post "/sessions" => 'users#sessions'
  get "/logout" => 'users#logout'
  get "/home" => 'users#home'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

HTML-CSS-JS/js-form/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

HTML-CSS-JS/js-form/app/models/user.rb
class User < ApplicationRecord
    has_one_attached :profile_image
end

HTML-CSS-JS/js-form/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

HTML-CSS-JS/js-form/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
    @user = User.new
    @page_var = 1
  end

  def create
    @user = User.new(user_params)

    @user.save
    reset_session
    redirect_to signin_url
  end

  def signin
    @page_var = 0
  end

  def sessions
    @user = User.find_by(email: params[:email])
    redirect_url = signin_url
    if @user && @user.password == params[:password]
      session[:user] = @user
      redirect_url = home_url
    end
    flash[:error] = "Invalid email or password."
    redirect_to redirect_url
  end

  def logout
    session[:user] = nil
    flash[:error] = ""
    redirect_to signin_url
  end

  def home
    u = session[:user]
    @user = User.find_by(email: u["email"])
  end


  private

  def user_params
    params.require(:user).permit(:email, :name, :phone, :password, :gender, :country, :profile_image)
  end
end

HTML-CSS-JS/js-form/app/helpers/application_helper.rb
module ApplicationHelper
end

HTML-CSS-JS/js-form/app/helpers/users_helper.rb
module UsersHelper
end

HTML-CSS-JS/js-form/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JsForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= javascript_include_tag 'custom' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

HTML-CSS-JS/js-form/app/views/users/_navbar.html.erb
<nav>
    <div class="company-name">TestGenius</div>
    <a href="#">Home</a>
    <a href="#">About</a>
    <a href="#">Services</a>
    <a href="#">Contact</a>
    <% if @page_var == 0 %>
    
    <%= link_to "Sign Up" , signup_path , class: "nav-signin" %>
    <% else %>
    
    <%= link_to "Sign In" , signin_path , class: "nav-signin" %>
    <% end %>
</nav>

HTML-CSS-JS/js-form/app/views/users/home.html.erb
<h1> home </h1>
<%= @user.email %>

<%= link_to "Logout", '/logout', style:"color:white; margin:10px;" %>

<% if @user.profile_image.attached? %>
<div class="image-container" >
<%= image_tag @user.profile_image, id: "img-tag" %>
</div>
<% end %>

HTML-CSS-JS/js-form/app/views/users/signin.html.erb
<%= render partial: 'navbar', locals: { variable_name: @page_var } %>

<div class="signin_box">
<%= form_with(url: sessions_path)  do |form| %>

    <div>
      <img src="https://img.freepik.com/free-vector/rocket-flying-moon-cartoon-vector-icon-illustration-technology-transportation-icon-isolated_138676-5157.jpg?size=338&ext=jpg&ga=GA1.1.1546980028.1703376000&semt=ais" alt="Rocket Logo" id="logo-div">
    </div>

    <div>
      <h4 style="margin-left:15px; font-family: 'Arial';">Log in to TestGenius</h4>

      <h5 style="color:grey; margin-left:25px;">Please enter your email </h5>
    </div>

    <div>
      <%= form.text_field :email , placeholder: "Enter your email" , class: "text-field" %>
    </div>
  
    <div>
      <%= form.text_field  :password , type:"password", placeholder: "Enter your password" , class: "text-field", id:"password" %>
      <span class="password-toggle" onclick="myFunction()">
        <i id="icon-tag" class="fa-solid fa-eye" ></i>
      </span>
      <br><br>
    </div>
  
    <div>
      <%= form.submit "Continue" , class: "login-button" %>
    </div>
    <% if flash[:error].present? %>
<% end %>
<div class="error" style="font-size:12px; margin-left:28px; color:black;">
<%= flash[:error] %>
</div>
<% end %>
</div>

<script>

</script>

HTML-CSS-JS/js-form/app/views/users/signup.html.erb
<%= render partial: 'navbar', locals: { variable_name: @page_var } %>

<div class="signup_box">
<%= form_with(model: @user, html: { id: 'registrationForm'}) do |form| %>

    <div>
      <img src="https://img.freepik.com/free-vector/rocket-flying-moon-cartoon-vector-icon-illustration-technology-transportation-icon-isolated_138676-5157.jpg?size=338&ext=jpg&ga=GA1.1.1546980028.1703376000&semt=ais" alt="Rocket Logo" id="logo-div">
    </div>

    <div>
      <h4 style="margin-left:15px; font-family: 'Arial';">Register to TestGenius</h4>

      <h5 style="color:grey; margin-left:25px;">Please enter asked details </h5>
    </div>

    <div style="display:flex; flex-direction:column; margin-bottom:5px; ">
      <%= form.text_field :email , placeholder: "Enter your email", class: "text-field", id:"email"  %>
      <span id="email-error-message" class="error-message" style="color:red; font-size:10px; margin-top:0;"></span>
    </div>
  
    <div>
      <%= form.text_field :name , placeholder: "Enter your first name", class: "text-field"  %>
    </div>

    <div>
      <%= form.text_field :phone , placeholder: "Enter phone number", class: "text-field", id:"phone"  %>
    </div>
  
    <div>
      <%= form.text_field :password , placeholder: "Enter password", class: "text-field", id:"password" %>
    </div>

    <div style="display:flex; flex-direction:column; margin-bottom:5px; ">
      <%= form.text_field :confirm_password , placeholder: "Confirm your password", class: "text-field", id:"confirm_password" %>
      <span id="password-match-error-message" class="error-message" style="color:red; font-size:10px; margin-top:0;" ></span>
    </div>

    <%= form.label :gender %>
    <div class="radio-buttons">
      <%= form.radio_button :gender, 'Male' %>
      <%= form.label :gender_male, 'Male' %>

      <%= form.radio_button :gender, 'Female' %>
      <%= form.label :gender_female, 'Female' %>

    </div>

    <div class="field">
        <%= form.label :country %>
        <%= form.select :country, ['India', 'Mexico', 'US', 'UK'] %>
    </div>

    <br>
    
    <div>
      <%= form.label :profile_image %>
      <br>
      <%= form.file_field :profile_image %>
    </div>
  
    <div style="margin-top:10px;">
      <%= form.submit "Continue" , class: "login-button" %>
    </div>
<% end %>
</div>