Rails/website/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :articles
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users
  root 'users#index'
  resources :ads
  concern :addable do
    resources :ads
  end
  resources :demo
  resources :magzines, concerns: :addable
  # resources :magzines do
  #   resources :ads
  # end
  
  # resources :users, path_names: { new: 'make', edit: 'change' } # this line is the resourceful route

  # resources :avneet, controller: 'users'
  # resources :photos, controller: 'users'
  # resource :user #this is a singulare resource route
  # resolve('User') { [:user] }

  resource :user , only: [:show,:new]

  # match '/website', to: Website, via: :all

  get 'practice/page'
  # get 'demo/index'
  resources :demo
  # match 'demo/:id', :to => 'demo#show', :via => :get
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

Rails/website/app/models/ad.rb
class Ad < ApplicationRecord
    belongs_to :magzine
end

Rails/website/app/models/author.rb
class Author < ApplicationRecord
  has_many :books, before_add: :check_credit_limit

  def check_credit_limit(book)
    puts "Adds a booooooooook!"
  end
end

Rails/website/app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
    scope :no_genre, -> { where(genre:nil) }
end

Rails/website/app/models/car.rb
class Car < Vehicle
end

Rails/website/app/models/city.rb
class City < ApplicationRecord
    # has_many :users
end

Rails/website/app/models/comment.rb
class Comment < ApplicationRecord
    include Entryable
end

Rails/website/app/models/create_customer.rb
class CreateCustomer < ApplicationRecord
end

Rails/website/app/models/customer.rb
class Customer < ApplicationRecord
end

Rails/website/app/models/demo.rb
class Demo < ApplicationRecord
end

Rails/website/app/models/employee.rb
class Employee < ApplicationRecord
    has_many :pictures, as: :imageable
end

Rails/website/app/models/entry.rb
module Entryable
  extend ActiveSupport::Concern

  included do
    has_one :entry, as: :entryable, touch: true
  end
end

class Entry < ApplicationRecord
  delegated_type :entryable, types: %w[ Message Comment ], dependent: :destroy
end

Rails/website/app/models/magzine.rb
class Magzine < ApplicationRecord
    has_many :ads
end

Rails/website/app/models/message.rb
class Message < ApplicationRecord
    include Entryable
end

Rails/website/app/models/order.rb
class Order < ApplicationRecord
end

Rails/website/app/models/person.rb
class Person < ApplicationRecord
end

Rails/website/app/models/picture.rb
class Picture < ApplicationRecord
    belongs_to :imageable, polymorphic: true
end

Rails/website/app/models/product.rb
class Product < ApplicationRecord
    has_many :pictures, as: :imageable
end

Rails/website/app/models/user.rb
class User < ApplicationRecord
  paginates_per 2
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :omniauthable, omniauth_providers: [:github]
  # belongs_to :city

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    unless user
      user = User.create(name: data['name'],
        email: data['email'],
        password: Devise.friendly_token[0,20]
      )
    end
    user
  end
end

Rails/website/app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

Rails/website/app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: %i[ show edit update destroy ]

  # GET /ads or /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1 or /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads or /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to ad_url(@ad), notice: "Ad was successfully created." }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1 or /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to ad_url(@ad), notice: "Ad was successfully updated." }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1 or /ads/1.json
  def destroy
    @ad.destroy!

    respond_to do |format|
      format.html { redirect_to ads_url, notice: "Ad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ad_params
      params.require(:ad).permit(:name)
    end
end

Rails/website/app/helpers/ads_helper.rb
module AdsHelper
end

Rails/website/app/helpers/demo_helper.rb
module DemoHelper
end

Rails/website/app/helpers/magzines_helper.rb
module MagzinesHelper
end

Rails/website/app/views/ads/_ad.html.erb
<div id="<%= dom_id ad %>">
  <p>
    <strong>Name:</strong>
    <%= ad.name %>
  </p>

</div>

Rails/website/app/views/ads/_form.html.erb
<%= form_with(model: ad) do |form| %>
  <% if ad.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
        <% ad.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Rails/website/app/views/ads/edit.html.erb
<h1>Editing ad</h1>

<%= render "form", ad: @ad %>

<br>

<div>
  <%= link_to "Show this ad", @ad %> |
  <%= link_to "Back to ads", ads_path %>
</div>

Rails/website/app/views/ads/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ads</h1>

<div id="ads">
  <% @ads.each do |ad| %>
    <%= render ad %>
    <p>
      <%= link_to "Show this ad", ad %>
    </p>
  <% end %>
</div>

<%= link_to "New ad", new_ad_path %>

Rails/website/app/views/ads/new.html.erb
<h1>New ad</h1>

<%= render "form", ad: @ad %>

<br>

<div>
  <%= link_to "Back to ads", ads_path %>
</div>

Rails/website/app/views/ads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ad %>

<div>
  <%= link_to "Edit this ad", edit_ad_path(@ad) %> |
  <%= link_to "Back to ads", ads_path %>

  <%= button_to "Destroy this ad", @ad, method: :delete %>
</div>